apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-cicd-app
  template:
    metadata:
      labels:
        app: python-cicd-app
    spec:
      containers:
        - name: python-cicd-app
          image: python-cicd-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: python-cicd-app-service
spec:
  type: NodePort
  selector:
    app: python-cicd-app
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001
